### PR TITLE
Fixes isolate error in Flutter 3.3.0

### PR DESCRIPTION
**Pull request by acoutts**
This is a WIP fix.

1. We need this PR to be merged and a new version of `flutter_isolate` to be published: https://github.com/rmawatson/flutter_isolate/pull/118
2. Breaking change: everyone must now add the following annotation to any method they pass to `IsolateHandler` as the callback to execute:
```dart
@pragma('vm:entry-point')
```
Background: https://github.com/dart-lang/sdk/issues/49181#issuecomment-1156337511

Will update the documentation before changing this from a draft.

### CODE REVIEW

**Comment by deakjahn** [comment]
Please, help me out with the background because I can't see clearly. Will a new version come from `flutter_isolate`? I'd be rather unwilling to refer to a github repo instead of the normal `pub.dev`. Or is this just a temporary fix that will be overridden shortly? What's the expected timeline?

(`.flutter-plugins-dependencies` shouldn't be included, this is just a secondary issue.)

**Comment by acoutts** [comment]
Yes we need to wait for a new pub release for `flutter_isolate`, then we can update this package. Nice spot on flutter-plugins-dependencies --- i will fix that when i update this PR once the flutter_isolate package is published.

For now Ieaving this open so others can use my git dependency as a workaround.

**Comment by deakjahn** [comment]
OK, I'll be on the lookout.

**Comment by deakjahn** [comment]
By the way, if we need to decorate the entry point from now on, either mention this in the README or, at least, don't let me forget to do so when we finish this operation. :-)

**Comment by deadsoul44** [comment]
I am using isolate_handler to use Firestore. It is working in debug mode but not working in release mode. Is this the reason? By the way, flutter_isolate fix was merged 7 days ago but not released.

**Comment by JamesMcIntosh** [comment]
Hi @acoutts & @deakjahn,
Are you able to use update the PR to use the new release of flutter_isolate 2.0.3 is now available?

https://pub.dev/packages/flutter_isolate/versions/2.0.3
https://github.com/rmawatson/flutter_isolate/pull/118

**Comment by acoutts** [comment]
Back from vacation.
Updated MR to use newly published version.
@deakjahn we are ready for a final review / merge now.

**Comment by deakjahn** [comment]
There's this single file that says it shouldn't be included at all. Could you remove it? Then I'll merge and publish. Thanks.

**Comment by deakjahn** [comment]
@acoutts There's this single file that says it shouldn't be included at all. Could you remove it? Then I'll merge and publish. Thanks.

**Comment by deakjahn** [comment]
@acoutts I'd be happy to go on with this. :-)

**Comment by acoutts** [comment]
Done 🙌

**Comment by akagupta9** [comment]
is it released?

**Comment by deakjahn** [comment]
Yes: https://pub.dev/packages/isolate_handler/changelog

**Pull request merged**
