### PR TITLE
Restoring functionality

### PR DESCRIPTION
**Pull request by deakjahn**
So, in the end, although a bit butchered, what remains works again. :-)

It depends on `flutter_isolate`, there is no need to duplicate functionality. It would be probably possible to merge `HandledIsolate` and `FlutterIsolate` into one but, well. One calls the other now, Handled creates Flutters instead of regular Isolates.

The last hurdle to overcome was the context that cannot be sent over in its own class because `FlutterIsolate` doesn't handle it that way. Fortunately, the `name` inside it wasn't actually used anywhere (or maybe it was in those parts you already removed? Possible).

Finally, now it can handle the platform calls all right. There is no need to separate your plugins as I mentioned in the middle, `flutter_isolate` comes with a custom registrator that can be used just for this.

My app's functionality has been restored, and if you merge this and test it slightly, we might be able to go back to that original thread and report that the problem is tackled once more. :-)

### CODE REVIEW

**Comment by raccoons-are-goofy** [comment]
This looks great, thank you! :+1: I also support relying on `flutter_isolate` instead of duplicating the functionality.

I assume this is a breaking change. Before I merge, can you make changes (if any needed) to the example to show its current use? Also, how are native calls made from within isolates using the PR?

**Comment by deakjahn** [comment]
OK, I will. But if you want a runnable example, not just a sample .dart, we have to add the usual android/ios stuff.

The calls are just the same, you simply use whatever plugin you want. We can pick the common example, `path_provider` as an example.

**Comment by raccoons-are-goofy** [comment]
The example is just for communicating between isolates without the native code. Just sending an `int`, adding one and getting the result. :) Take a look at `example/example.dart` and make any changes necessary for it to work with the new code.

So for making native calls, all you do is make the call from within the isolate? That's great!

**Comment by deakjahn** [comment]
No, what I meant was that if you expect the example to be a full blown app that can be run, as is normally customary with plugins (also to create a test bed for yourself), then we had to add it. I did.

I still have some small problems with it, it complains about the usual `WidgetsFlutterBinding.ensureInitialized()` but `flutter_isolate` does call it.

**Comment by deakjahn** [comment]
It helps if I add an UI. :-)

**Comment by deakjahn** [comment]
I can't check the iOS version so either you can or we have to assume that it works.

**Comment by raccoons-are-goofy** [comment]
The main example is without native or UI code to make it as basic as possible for people only interested in using Isolate Handler for communication between isolates. The additional sample with native code is definitely good to have as well to show its use with native calls too.

Great job! 👍 I will merge and take a look at it and publish when ready. :)

**Comment by deakjahn** [comment]
Well, it no longer is without UI. :-)

**Comment by deakjahn** [comment]
Then you might want to put back that example as well but the current one might be enough, I don't know. It's simple enough as it is.

**Comment by raccoons-are-goofy** [comment]
Oh, you removed the original. Yes, it needs to be replaced as `pub.dev` requires an `example/example.dart` be present.

While the UI sample is simple enough, it may be difficult for people new to the package to see how it fits their needs if inter-isolate communication is their sole goal. More documentation is (almost) always better.

**Comment by deakjahn** [comment]
I simply moved it into `lib` and added the UI. Then restore it for sure.

**Comment by deakjahn** [comment]
However, then make sure you point out in the readme that while simple isolates work in a simpler environment, using plugins requires the UI to be present. Or, you can manually add the `WidgetsFlutterBinding` doohicky as the first line of the isolate, that might work just as well.

**Pull request merged**
